//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KidsUEntities1 : DbContext
    {
        public KidsUEntities1()
            : base("name=KidsUEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<language_arts> language_arts { get; set; }
        public virtual DbSet<math> maths { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<outcome_measurement> outcome_measurement { get; set; }
        public virtual DbSet<program_facility_sites> program_facility_sites { get; set; }
        public virtual DbSet<reading> readings { get; set; }
        public virtual DbSet<report_card> report_card { get; set; }
        public virtual DbSet<school_districts> school_districts { get; set; }
        public virtual DbSet<school> schools { get; set; }
        public virtual DbSet<staff_directory> staff_directory { get; set; }
        public virtual DbSet<student> students { get; set; }
    }
}
