//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class language_arts
    {
        public Nullable<int> first { get; set; }
        public Nullable<int> second { get; set; }
        public Nullable<int> third { get; set; }
        public Nullable<int> fourth { get; set; }
        public Nullable<int> fifth { get; set; }
        public int semester { get; set; }
        public int student_Unique_ID { get; set; }
    
        public virtual report_card report_card { get; set; }
    }
}
