//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class outcome_measurement
    {
        public string grade { get; set; }
        public int math_Pre_Test { get; set; }
        public int math_Post_Test { get; set; }
        public int language_Pre_Test { get; set; }
        public int language_Post_Test { get; set; }
        public int reading_Pre_Test { get; set; }
        public int reading_Fluency_Test_1 { get; set; }
        public int reading_Fluency_Test_2 { get; set; }
        public int reading_Fluency_Test_3 { get; set; }
        public int self_Esteem_Pre_Test { get; set; }
        public int self_Esteem_Post_Test { get; set; }
        public int student_Unique_ID { get; set; }
    
        public virtual student student { get; set; }
    }
}
