//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_directory
    {
        public string email { get; set; }
        public string assigned_site { get; set; }
        public string role { get; set; }
        public byte is_Active { get; set; }
    }
}
